In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('training_set_features.csv')

In [3]:
df2 = pd.read_csv('training_set_labels.csv')

In [4]:
df = pd.merge(df1, df2, on='respondent_id')
df

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation,xyz_vaccine,seasonal_vaccine
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN,0,0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe,0,1
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo,0,0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN,0,1
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,Own,Not in Labor Force,qufhixun,Non-MSA,0.0,0.0,NaN,NaN,0,0
26703,26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,Rent,Employed,lzgpxyit,"MSA, Principle City",1.0,0.0,fcxhlnwr,cmhcxjea,0,0
26704,26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,Own,NaN,lzgpxyit,"MSA, Not Principle City",0.0,0.0,NaN,NaN,0,1
26705,26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,...,Rent,Employed,lrircsnp,Non-MSA,1.0,0.0,fcxhlnwr,haliazsg,0,0
26706,26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,Own,Not in Labor Force,mlyzmhmf,"MSA, Principle City",1.0,0.0,NaN,NaN,0,0

In [5]:
df.drop(['employment_industry', 'household_children', 'household_adults', 'census_msa', 'hhs_geo_region', 'employment_status', 'rent_or_own', 'health_insurance', 'education', 'race', 'sex', 'income_poverty', 'marital_status', 'employment_occupation'], axis='columns', inplace=True)
df.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,health_worker,opinion_xyz_vacc_effective,opinion_xyz_risk,opinion_xyz_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,age_group,xyz_vaccine,seasonal_vaccine
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,3.0,1.0,2.0,2.0,1.0,2.0,55 - 64 Years,0,0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,0.0,5.0,4.0,4.0,4.0,2.0,4.0,35 - 44 Years,0,1
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,1.0,1.0,4.0,1.0,2.0,18 - 34 Years,0,0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,3.0,3.0,5.0,5.0,4.0,1.0,65+ Years,0,1
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,3.0,3.0,2.0,3.0,1.0,4.0,45 - 54 Years,0,0

In [6]:
df = df.dropna(axis=0, how='any')
df.columns[df.isna().any()]

Index([], dtype='object')

In [7]:
dummies = pd.get_dummies(df.age_group)
dummies.head(3)

   18 - 34 Years  35 - 44 Years  45 - 54 Years  55 - 64 Years  65+ Years
0          False          False          False           True      False
1          False           True          False          False      False
3          False          False          False          False       True

In [8]:
df = pd.concat([df,dummies],axis='columns')
df.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,opinion_seas_risk,opinion_seas_sick_from_vacc,age_group,xyz_vaccine,seasonal_vaccine,18 - 34 Years,35 - 44 Years,45 - 54 Years,55 - 64 Years,65+ Years
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,2.0,55 - 64 Years,0,0,False,False,False,True,False
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,2.0,4.0,35 - 44 Years,0,1,False,True,False,False,False
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,4.0,1.0,65+ Years,0,1,False,False,False,False,True
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,1.0,4.0,45 - 54 Years,0,0,False,False,True,False,False
5,5,3.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,4.0,4.0,65+ Years,0,0,False,False,False,False,True

In [9]:
df.drop('age_group',axis='columns',inplace=True)
df.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,xyz_vaccine,seasonal_vaccine,18 - 34 Years,35 - 44 Years,45 - 54 Years,55 - 64 Years,65+ Years
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,2.0,1.0,2.0,0,0,False,False,False,True,False
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,4.0,2.0,4.0,0,1,False,True,False,False,False
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,5.0,4.0,1.0,0,1,False,False,False,False,True
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,3.0,1.0,4.0,0,0,False,False,True,False,False
5,5,3.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,5.0,4.0,4.0,0,0,False,False,False,False,True

In [10]:
inputs1 = df.drop(['xyz_vaccine', 'seasonal_vaccine', 'opinion_seas_vacc_effective', 'opinion_seas_risk', 'opinion_seas_sick_from_vacc'], axis='columns')
inputs2 = df.drop(['xyz_vaccine', 'seasonal_vaccine', 'opinion_xyz_vacc_effective', 'opinion_xyz_risk', 'opinion_xyz_sick_from_vacc'], axis='columns')
target = df.xyz_vaccine
target2 = df.seasonal_vaccine

In [11]:
inputs1.columns[inputs1.isna().any()]

Index([], dtype='object')

In [12]:
inputs2.columns[inputs2.isna().any()]

Index([], dtype='object')

In [13]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

model.fit(inputs, target)

In [14]:
test = pd.read_csv('test_set_features.csv')
test.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"> $75,000",Not Married,Rent,Employed,mlyzmhmf,"MSA, Not Principle City",1.0,0.0,atmlpfrs,hfxkjkmi
1,26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,Non-MSA,3.0,0.0,atmlpfrs,xqwwgdyp
2,26709,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,"> $75,000",Married,Own,Employed,lrircsnp,Non-MSA,1.0,0.0,nduyfdeo,pvmttkik
3,26710,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,lrircsnp,"MSA, Not Principle City",1.0,0.0,NaN,NaN
4,26711,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,lzgpxyit,Non-MSA,0.0,1.0,fcxhlnwr,mxkfnird

In [15]:
test.drop(['employment_industry', 'household_children', 'household_adults', 'census_msa', 'hhs_geo_region', 'employment_status', 'rent_or_own', 'health_insurance', 'education', 'race', 'sex', 'income_poverty', 'marital_status', 'employment_occupation'], axis='columns', inplace=True)
test.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,chronic_med_condition,child_under_6_months,health_worker,opinion_xyz_vacc_effective,opinion_xyz_risk,opinion_xyz_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,age_group
0,26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,5.0,1.0,1.0,5.0,1.0,1.0,35 - 44 Years
1,26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,4.0,1.0,1.0,4.0,1.0,1.0,18 - 34 Years
2,26709,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,5.0,4.0,2.0,5.0,4.0,4.0,55 - 64 Years
3,26710,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,4.0,2.0,2.0,4.0,4.0,2.0,65+ Years
4,26711,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,5.0,2.0,4.0,4.0,4.0,2.0,35 - 44 Years

In [16]:
dummy = pd.get_dummies(test.age_group)
dummy.head(3)

   18 - 34 Years  35 - 44 Years  45 - 54 Years  55 - 64 Years  65+ Years
0          False           True          False          False      False
1           True          False          False          False      False
2          False          False          False           True      False

In [17]:
test = pd.concat([test,dummies],axis='columns')
test.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,opinion_xyz_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,age_group,18 - 34 Years,35 - 44 Years,45 - 54 Years,55 - 64 Years,65+ Years
0,26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,1.0,5.0,1.0,1.0,35 - 44 Years,False,False,False,True,False
1,26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,4.0,1.0,1.0,18 - 34 Years,False,True,False,False,False
2,26709,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,2.0,5.0,4.0,4.0,55 - 64 Years,NaN,NaN,NaN,NaN,NaN
3,26710,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,4.0,4.0,2.0,65+ Years,False,False,False,False,True
4,26711,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,4.0,4.0,4.0,2.0,35 - 44 Years,False,False,True,False,False

In [18]:
test.drop('age_group',axis='columns',inplace=True)
test.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,opinion_xyz_risk,opinion_xyz_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,18 - 34 Years,35 - 44 Years,45 - 54 Years,55 - 64 Years,65+ Years
0,26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,1.0,1.0,5.0,1.0,1.0,False,False,False,True,False
1,26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,4.0,1.0,1.0,False,True,False,False,False
2,26709,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,4.0,2.0,5.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN
3,26710,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,4.0,4.0,2.0,False,False,False,False,True
4,26711,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,2.0,4.0,4.0,4.0,2.0,False,False,True,False,False

In [19]:
test = test.dropna(axis=0, how='any')

In [20]:
test.columns[test.isna().any()]

Index([], dtype='object')

In [21]:
test1 = test.drop(['opinion_seas_vacc_effective', 'opinion_seas_risk', 'opinion_seas_sick_from_vacc'], axis='columns')
test2 = test.drop(['opinion_xyz_vacc_effective', 'opinion_xyz_risk', 'opinion_xyz_sick_from_vacc'], axis='columns')

In [22]:
model.fit(inputs1, target)

GaussianNB()

In [23]:
model.score(inputs1, target)

0.7969905192658955

In [24]:
result1 = model.predict_proba(test1)
result1

array([[0.92275713, 0.07724287],
       [0.99717062, 0.00282938],
       [0.8175425 , 0.1824575 ],
       ...,
       [0.68386106, 0.31613894],
       [0.75949056, 0.24050944],
       [0.98344882, 0.01655118]])

In [25]:
model.fit(inputs2, target2)

GaussianNB()

In [26]:
model.score(inputs2, target2)

0.7529355484039315

In [29]:
result2 = model.predict_proba(test2)
result2

array([[0.61175531, 0.38824469],
       [0.99295414, 0.00704586],
       [0.04653481, 0.95346519],
       ...,
       [0.52188472, 0.47811528],
       [0.15193181, 0.84806819],
       [0.30310169, 0.69689831]])

In [30]:
resdf1 = pd.DataFrame(result1)
resdf1

              0         1
0      0.922757  0.077243
1      0.997171  0.002829
2      0.817543  0.182457
3      0.372635  0.627365
4      0.368576  0.631424
...         ...       ...
19776  0.810270  0.189730
19777  0.821015  0.178985
19778  0.683861  0.316139
19779  0.759491  0.240509
19780  0.983449  0.016551

[19781 rows x 2 columns]

In [38]:
resdf1 = resdf1.drop(1, axis='columns')

In [39]:
resdf1.rename(columns={0: 'h1n1_vaccine'}, inplace=True)
resdf1

       h1n1_vaccine
0          0.922757
1          0.997171
2          0.817543
3          0.372635
4          0.368576
...             ...
19776      0.810270
19777      0.821015
19778      0.683861
19779      0.759491
19780      0.983449

[19781 rows x 1 columns]

In [34]:
resdf2 = pd.DataFrame(result2)
resdf2

              0         1
0      0.611755  0.388245
1      0.992954  0.007046
2      0.046535  0.953465
3      0.132235  0.867765
4      0.007201  0.992799
...         ...       ...
19776  0.999324  0.000676
19777  0.343608  0.656392
19778  0.521885  0.478115
19779  0.151932  0.848068
19780  0.303102  0.696898

[19781 rows x 2 columns]

In [40]:
resdf2 = resdf2.drop(1, axis='columns')

In [41]:
resdf2.rename(columns={0: 'seasonal_vaccine'}, inplace=True)
resdf2

       seasonal_vaccine
0              0.611755
1              0.992954
2              0.046535
3              0.132235
4              0.007201
...                 ...
19776          0.999324
19777          0.343608
19778          0.521885
19779          0.151932
19780          0.303102

[19781 rows x 1 columns]

In [51]:
tempdf = pd.read_csv('submission_format.csv')
tempdf = tempdf.drop(['h1n1_vaccine', 'seasonal_vaccine'], axis='columns')
tempdf

       respondent_id
0              26707
1              26708
2              26709
3              26710
4              26711
...              ...
26703          53410
26704          53411
26705          53412
26706          53413
26707          53414

[26708 rows x 1 columns]

In [57]:
result = pd.concat([tempdf, resdf1, resdf2], axis=1)
result

       respondent_id  h1n1_vaccine  seasonal_vaccine
0              26707      0.922757          0.611755
1              26708      0.997171          0.992954
2              26709      0.817543          0.046535
3              26710      0.372635          0.132235
4              26711      0.368576          0.007201
...              ...           ...               ...
26703          53410           NaN               NaN
26704          53411           NaN               NaN
26705          53412           NaN               NaN
26706          53413           NaN               NaN
26707          53414           NaN               NaN

[26708 rows x 3 columns]

In [58]:
result.to_csv('Result.csv')